version: 3
services:
  web:
    build: ./web
    command: python -u ./web/app.py
    ports:
        - "5000:5000"
    volumes:
        - .:/src
    links:
        - mongo
        - redis
  mongo:
    image: mongo:3.0.2

  redis:
    image: redis
